from __future__ import annotations

import re
import uuid
from dataclasses import dataclass, asdict, field
from typing import Dict, List, Tuple, Optional, Set, Any

from node_library import NODE_LIBRARY


def new_id() -> str:
    return uuid.uuid4().hex


def types_compatible(output_type: str, input_type: str) -> bool:
    # Exec pins must match exec pins only
    if output_type == "exec" or input_type == "exec":
        return output_type == "exec" and input_type == "exec"

    # "any" matches anything (non-exec)
    if output_type == "any" or input_type == "any":
        return True

    return output_type == input_type


def sanitize_identifier(name: str, fallback: str = "x") -> str:
    s = (name or "").strip()
    if not s:
        return fallback
    s = re.sub(r"[^0-9a-zA-Z_]", "_", s)
    if re.match(r"^[0-9]", s):
        s = "_" + s
    return s if s.isidentifier() else fallback


@dataclass
class PinData:
    pin_id: str
    name: str
    pin_type: str
    is_output: bool


@dataclass
class NodeData:
    node_id: str
    kind: str
    title: str
    x: float
    y: float
    inputs: List[PinData]
    outputs: List[PinData]
    props: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ConnectionData:
    out_pin_id: str
    in_pin_id: str


@dataclass
class GraphWarning:
    node_id: str
    code: str
    message: str
    pin_id: Optional[str] = None


class CodeWriter:
    def __init__(self) -> None:
        self.lines: List[str] = []
        self.indent: int = 0

    def push(self) -> None:
        self.indent += 4

    def pop(self) -> None:
        self.indent = max(0, self.indent - 4)

    def write(self, line: str = "") -> None:
        pad = " " * self.indent
        self.lines.append(pad + line if line else "")


class BaseRenderer:
    profile: str = "python"

    def __init__(self, w: CodeWriter) -> None:
        self.w = w
        self.declared_vars: Set[str] = set()

    def header(self) -> List[str]:
        return ["# Auto-generated by FlowPins", ""]

    def runtime_helpers(self) -> List[str]:
        return []

    def warning_comment_prefix(self) -> str:
        return "#"

    def emit_assign(self, name: str, expr: str) -> None:
        raise NotImplementedError

    def emit_print(self, expr: str) -> None:
        raise NotImplementedError

    def begin_if(self, cond_expr: str) -> None:
        raise NotImplementedError

    def else_block(self) -> None:
        raise NotImplementedError

    def end_if(self) -> None:
        return

    def begin_for_range(self, loop_var: str, start_expr: str, end_expr: str) -> None:
        raise NotImplementedError

    def end_for_range(self) -> None:
        return

    def emit_break(self) -> None:
        raise NotImplementedError

    def emit_continue(self) -> None:
        raise NotImplementedError

    def emit_pass(self) -> None:
        raise NotImplementedError

    def begin_function(self, name: str) -> None:
        raise NotImplementedError

    def end_function(self) -> None:
        raise NotImplementedError

    def emit_call(self, name: str) -> None:
        raise NotImplementedError


class PythonRenderer(BaseRenderer):
    profile = "python"

    def runtime_helpers(self) -> List[str]:
        return [
            "def __fp_list_get(lst, idx):",
            "    try:",
            "        if lst is None:",
            "            return None",
            "        return lst[idx]",
            "    except Exception:",
            "        return None",
            "",
            "def __fp_list_len(lst):",
            "    try:",
            "        if lst is None:",
            "            return 0",
            "        return len(lst)",
            "    except Exception:",
            "        return 0",
            "",
            "def __fp_map_get(mp, key):",
            "    try:",
            "        if mp is None:",
            "            return None",
            "        return mp.get(key) if hasattr(mp, 'get') else None",
            "    except Exception:",
            "        return None",
            "",
            "def __fp_list_append(lst, val):",
            "    try:",
            "        if lst is None:",
            "            return",
            "        lst.append(val)",
            "    except Exception:",
            "        return",
            "",
            "def __fp_map_set(mp, key, val):",
            "    try:",
            "        if mp is None:",
            "            return",
            "        mp[key] = val",
            "    except Exception:",
            "        return",
            "",
            "def __fp_map_items(mp):",
            "    try:",
            "        if mp is None:",
            "            return []",
            "        if hasattr(mp, 'items'):",
            "            return list(mp.items())",
            "        return []",
            "    except Exception:",
            "        return []",
            "",
        ]

    def emit_assign(self, name: str, expr: str) -> None:
        self.w.write(f"{name} = {expr}")

    def emit_print(self, expr: str) -> None:
        self.w.write(f"print({expr})")

    def begin_if(self, cond_expr: str) -> None:
        self.w.write(f"if ({cond_expr}):")
        self.w.push()

    def else_block(self) -> None:
        self.w.pop()
        self.w.write("else:")
        self.w.push()

    def end_if(self) -> None:
        self.w.pop()

    def begin_for_range(self, loop_var: str, start_expr: str, end_expr: str) -> None:
        self.w.write(f"for {loop_var} in range({start_expr}, {end_expr}):")
        self.w.push()

    def end_for_range(self) -> None:
        self.w.pop()

    def emit_break(self) -> None:
        self.w.write("break")

    def emit_continue(self) -> None:
        self.w.write("continue")

    def emit_pass(self) -> None:
        self.w.write("pass")

    def begin_function(self, name: str) -> None:
        self.w.write(f"def {name}():")
        self.w.push()

    def end_function(self) -> None:
        self.w.pop()
        self.w.write("")

    def emit_call(self, name: str) -> None:
        self.w.write(f"{name}()")


class MayaPythonRenderer(PythonRenderer):
    profile = "maya_python"

    def header(self) -> List[str]:
        return [
            "# Auto-generated by FlowPins (Maya Python)",
            "# Paste into Maya Script Editor (Python) and run",
            "",
            "try:",
            "    import maya.cmds as cmds",
            "except Exception as e:",
            "    raise RuntimeError('This script must be run inside Maya (maya.cmds not found).') from e",
            "",
        ]


class ToonBoomJSRenderer(BaseRenderer):
    profile = "toonboom_js"

    def header(self) -> List[str]:
        return ["// Auto-generated by FlowPins (Toon Boom JS)", ""]

    def warning_comment_prefix(self) -> str:
        return "//"

    def runtime_helpers(self) -> List[str]:
        return [
            "function __fp_list_get(lst, idx) {",
            "    try {",
            "        if (!lst) return null;",
            "        if (idx === undefined || idx === null) return null;",
            "        var i = Number(idx);",
            "        if (isNaN(i)) return null;",
            "        i = Math.floor(i);",
            "        if (i < 0 || i >= lst.length) return null;",
            "        return lst[i];",
            "    } catch (e) {",
            "        return null;",
            "    }",
            "}",
            "",
            "function __fp_list_len(lst) {",
            "    try {",
            "        if (!lst) return 0;",
            "        return lst.length;",
            "    } catch (e) {",
            "        return 0;",
            "    }",
            "}",
            "",
            "function __fp_map_get(mp, key) {",
            "    try {",
            "        if (!mp) return null;",
            "        if (key === undefined || key === null) return null;",
            "        var v = mp[key];",
            "        return (v === undefined) ? null : v;",
            "    } catch (e) {",
            "        return null;",
            "    }",
            "}",
            "",
            "function __fp_list_append(lst, val) {",
            "    try {",
            "        if (!lst) return;",
            "        lst.push(val);",
            "    } catch (e) {",
            "        return;",
            "    }",
            "}",
            "",
            "function __fp_map_set(mp, key, val) {",
            "    try {",
            "        if (!mp) return;",
            "        mp[key] = val;",
            "    } catch (e) {",
            "        return;",
            "    }",
            "}",
            "",
            "function __fp_map_keys(mp) {",
            "    try {",
            "        if (!mp) return [];",
            "        var keys = [];",
            "        for (var k in mp) {",
            "            if (mp.hasOwnProperty(k)) keys.push(k);",
            "        }",
            "        return keys;",
            "    } catch (e) {",
            "        return [];",
            "    }",
            "}",
            "",
        ]

    def emit_assign(self, name: str, expr: str) -> None:
        if name not in self.declared_vars:
            self.declared_vars.add(name)
            self.w.write(f"var {name} = {expr};")
        else:
            self.w.write(f"{name} = {expr};")

    def emit_print(self, expr: str) -> None:
        self.w.write(f"MessageLog.trace({expr});")

    def begin_function(self, name: str) -> None:
        self.w.write(f"function {name}() {{")
        self.w.push()

    def end_function(self) -> None:
        self.w.pop()
        self.w.write("}")
        self.w.write("")

    def emit_call(self, name: str) -> None:
        self.w.write(f"{name}();")

    def begin_if(self, cond_expr: str) -> None:
        self.w.write(f"if ({cond_expr}) {{")
        self.w.push()

    def else_block(self) -> None:
        self.w.pop()
        self.w.write("} else {")
        self.w.push()

    def end_if(self) -> None:
        self.w.pop()
        self.w.write("}")

    def begin_for_range(self, loop_var: str, start_expr: str, end_expr: str) -> None:
        self.w.write(f"for (var {loop_var} = {start_expr}; {loop_var} < {end_expr}; {loop_var}++) {{")
        self.w.push()

    def end_for_range(self) -> None:
        self.w.pop()
        self.w.write("}")

    def emit_break(self) -> None:
        self.w.write("break;")

    def emit_continue(self) -> None:
        self.w.write("continue;")

    def emit_pass(self) -> None:
        self.w.write(";")


class GraphModel:
    def __init__(self):
        self.nodes: Dict[str, NodeData] = {}
        self.connections: List[ConnectionData] = []
        self.warnings: List[GraphWarning] = []

    def clear(self) -> None:
        self.nodes.clear()
        self.connections.clear()
        self.warnings.clear()

    def clear_warnings(self) -> None:
        self.warnings.clear()

    def get_warnings(self) -> List[GraphWarning]:
        return list(self.warnings)

    def _warn(self, node: Optional[NodeData], code: str, message: str, pin_id: Optional[str] = None) -> None:
        nid = node.node_id if node else ""
        self.warnings.append(GraphWarning(node_id=nid, code=code, message=message, pin_id=pin_id))

    # -----------------------------
    # Save / Load
    # -----------------------------
    def to_dict(self) -> dict:
        return {
            "nodes": [
                {
                    "node_id": n.node_id,
                    "kind": n.kind,
                    "title": n.title,
                    "x": n.x,
                    "y": n.y,
                    "inputs": [asdict(p) for p in n.inputs],
                    "outputs": [asdict(p) for p in n.outputs],
                    "props": n.props,
                }
                for n in self.nodes.values()
            ],
            "connections": [asdict(c) for c in self.connections],
        }

    @staticmethod
    def from_dict(d: dict) -> "GraphModel":
        gm = GraphModel()
        for n in d.get("nodes", []):
            inputs = [PinData(**p) for p in n.get("inputs", [])]
            outputs = [PinData(**p) for p in n.get("outputs", [])]
            nd = NodeData(
                node_id=n["node_id"],
                kind=n.get("kind", "unknown"),
                title=n.get("title", n.get("kind", "Node")),
                x=float(n.get("x", 0.0)),
                y=float(n.get("y", 0.0)),
                inputs=inputs,
                outputs=outputs,
                props=n.get("props", {}) or {},
            )
            gm.nodes[nd.node_id] = nd
        gm.connections = [ConnectionData(**c) for c in d.get("connections", [])]
        return gm

    # -----------------------------
    # Connections
    # -----------------------------
    def add_connection(self, out_pin_id: str, in_pin_id: str) -> None:
        self.connections = [c for c in self.connections if c.in_pin_id != in_pin_id]
        for c in self.connections:
            if c.out_pin_id == out_pin_id and c.in_pin_id == in_pin_id:
                return
        self.connections.append(ConnectionData(out_pin_id=out_pin_id, in_pin_id=in_pin_id))

    def remove_connection(self, out_pin_id: str, in_pin_id: str) -> None:
        self.connections = [
            c for c in self.connections
            if not (c.out_pin_id == out_pin_id and c.in_pin_id == in_pin_id)
        ]

    def remove_connections_for_pin(self, pin_id: str) -> None:
        self.connections = [
            c for c in self.connections
            if c.out_pin_id != pin_id and c.in_pin_id != pin_id
        ]

    # -----------------------------
    # Nodes
    # -----------------------------
    def remove_node(self, node_id: str) -> None:
        node = self.nodes.get(node_id)
        if not node:
            return
        for p in node.inputs + node.outputs:
            self.remove_connections_for_pin(p.pin_id)
        self.nodes.pop(node_id, None)

    def create_node(self, kind: str, x: float, y: float) -> NodeData:
        spec = NODE_LIBRARY[kind]
        node_id = new_id()

        inputs = [PinData(pin_id=new_id(), name=p.name, pin_type=p.pin_type, is_output=False) for p in spec.inputs]
        outputs = [PinData(pin_id=new_id(), name=p.name, pin_type=p.pin_type, is_output=True) for p in spec.outputs]

        nd = NodeData(
            node_id=node_id,
            kind=kind,
            title=spec.title,
            x=float(x),
            y=float(y),
            inputs=inputs,
            outputs=outputs,
            props=dict(spec.default_props),
        )
        self.nodes[nd.node_id] = nd
        return nd

    # -----------------------------
    # Clone
    # -----------------------------
    def clone_node(self, node_id: str, dx: float = 40, dy: float = 40) -> str:
        src = self.nodes.get(node_id)
        if not src:
            raise KeyError(f"Node not found: {node_id}")

        new_node_id = new_id()

        new_inputs = [
            PinData(pin_id=new_id(), name=p.name, pin_type=p.pin_type, is_output=False)
            for p in src.inputs
        ]
        new_outputs = [
            PinData(pin_id=new_id(), name=p.name, pin_type=p.pin_type, is_output=True)
            for p in src.outputs
        ]

        cloned = NodeData(
            node_id=new_node_id,
            kind=src.kind,
            title=src.title,
            x=float(src.x + dx),
            y=float(src.y + dy),
            inputs=new_inputs,
            outputs=new_outputs,
            props=dict(src.props),
        )

        self.nodes[cloned.node_id] = cloned
        return cloned.node_id

    def clone_selection_with_wires(self, node_ids: List[str], dx: float = 40, dy: float = 40) -> List[str]:
        node_map: Dict[str, str] = {}
        for nid in node_ids:
            node_map[nid] = self.clone_node(nid, dx=dx, dy=dy)

        pin_map: Dict[str, str] = {}
        for old_nid, new_nid in node_map.items():
            old_node = self.nodes[old_nid]
            new_node = self.nodes[new_nid]

            for i, p in enumerate(old_node.inputs):
                pin_map[p.pin_id] = new_node.inputs[i].pin_id
            for i, p in enumerate(old_node.outputs):
                pin_map[p.pin_id] = new_node.outputs[i].pin_id

        for c in list(self.connections):
            if c.out_pin_id in pin_map and c.in_pin_id in pin_map:
                self.add_connection(pin_map[c.out_pin_id], pin_map[c.in_pin_id])

        return [node_map[nid] for nid in node_ids]

    # -----------------------------
    # Export entrypoints
    # -----------------------------
    def export_text(self, profile: str = "python") -> str:
        self.clear_warnings()

        profile = (profile or "python").strip().lower()
        if profile in ("py", "python"):
            renderer: BaseRenderer = PythonRenderer(CodeWriter())
        elif profile in ("maya", "maya_python", "maya-py"):
            renderer = MayaPythonRenderer(CodeWriter())
        elif profile in ("toonboom", "toonboom_js", "tb_js", "js"):
            renderer = ToonBoomJSRenderer(CodeWriter())
        else:
            renderer = PythonRenderer(CodeWriter())

        if any(n.kind == "start" for n in self.nodes.values()):
            lines, errors = self._export_exec(renderer)
        else:
            lines, errors = self._export_expr(renderer)

        if errors:
            err_text = "\n".join(errors).replace('"', '\\"')
            return "# Auto-generated by FlowPins\n" + f'raise SystemExit("Export failed:\\n{err_text}")\n'

        if self.warnings:
            prefix = renderer.warning_comment_prefix()
            warn_lines = [f"{prefix} Warnings:"] + [
                f"{prefix} - [{w.code}] {w.message}" for w in self.warnings
            ] + [""]

            lines = warn_lines + lines

        return "\n".join(lines) + "\n"

    def export_python_text(self) -> str:
        return self.export_text("python")

    def export_maya_python_text(self) -> str:
        return self.export_text("maya_python")

    def export_toonboom_js_text(self) -> str:
        return self.export_text("toonboom_js")

    # -----------------------------
    # Common maps
    # -----------------------------
    def _pin_to_node_map(self) -> Dict[str, Tuple[str, bool, str, str]]:
        m: Dict[str, Tuple[str, bool, str, str]] = {}
        for nid, n in self.nodes.items():
            for p in (n.inputs + n.outputs):
                m[p.pin_id] = (nid, p.is_output, p.pin_type, p.name)
        return m

    def _split_connections(
        self,
        pin_to_node: Dict[str, Tuple[str, bool, str, str]],
    ) -> Tuple[Dict[str, str], Dict[str, str], List[str]]:
        errors: List[str] = []
        exec_in_to_out: Dict[str, str] = {}
        data_in_to_out: Dict[str, str] = {}

        for c in self.connections:
            if c.out_pin_id not in pin_to_node or c.in_pin_id not in pin_to_node:
                continue
            _, out_is_output, out_type, _ = pin_to_node[c.out_pin_id]
            _, in_is_output, in_type, _ = pin_to_node[c.in_pin_id]

            if not out_is_output or in_is_output:
                continue

            if not types_compatible(out_type, in_type):
                errors.append(f"Type mismatch: {out_type} -> {in_type}")

            if out_type == "exec" or in_type == "exec":
                exec_in_to_out[c.in_pin_id] = c.out_pin_id
            else:
                data_in_to_out[c.in_pin_id] = c.out_pin_id

        return exec_in_to_out, data_in_to_out, errors

    # -----------------------------
    # Expression export
    # -----------------------------
    def _export_expr(self, r: BaseRenderer) -> Tuple[List[str], List[str]]:
        errors: List[str] = []
        pin_to_node = self._pin_to_node_map()
        _, data_in_to_out, split_err = self._split_connections(pin_to_node)
        errors.extend(split_err)

        out_expr, expr_lines, expr_err = self._build_data_expressions(r, pin_to_node, data_in_to_out)
        errors.extend(expr_err)

        lines = r.header()
        rh = r.runtime_helpers()
        lines.extend(rh)
        if rh:
            lines.append("")
        lines.extend(expr_lines)
        if expr_lines:
            lines.append("")

        for n in self.nodes.values():
            if n.kind == "print":
                v = self._resolve_input_expr(n, "value", pin_to_node, data_in_to_out, out_expr, errors)
                if v is not None:
                    r.emit_print(v)

        lines.extend(r.w.lines)
        return lines, errors

    # -----------------------------
    # Exec export
    # -----------------------------
    def _export_exec(self, r: BaseRenderer) -> Tuple[List[str], List[str]]:
        w = r.w
        errors: List[str] = []

        pin_to_node = self._pin_to_node_map()
        exec_in_to_out, data_in_to_out, split_err = self._split_connections(pin_to_node)
        errors.extend(split_err)

        # Data graph expressions (consts, math, get_var, loop index outputs, etc)
        out_expr, expr_lines, expr_err = self._build_data_expressions(r, pin_to_node, data_in_to_out)
        errors.extend(expr_err)

        # NEW: runtime expressions produced by exec nodes (so their outputs can be wired)
        exec_out_expr: Dict[str, str] = {}

        start_nodes = [n for n in self.nodes.values() if n.kind == "start"]
        if not start_nodes:
            errors.append("No Start node found.")
            lines = r.header()
            rh = r.runtime_helpers()
            lines.extend(rh)
            if rh:
                lines.append("")
            lines.extend(expr_lines)
            return lines, errors
        if len(start_nodes) > 1:
            errors.append("Multiple Start nodes found. Keep only one.")
            lines = r.header()
            rh = r.runtime_helpers()
            lines.extend(rh)
            if rh:
                lines.append("")
            lines.extend(expr_lines)
            return lines, errors

        start = start_nodes[0]
        start_exec_out = start.outputs[0].pin_id if start.outputs else None
        if not start_exec_out:
            errors.append("Start node missing exec output.")
            lines = r.header()
            rh = r.runtime_helpers()
            lines.extend(rh)
            if rh:
                lines.append("")
            lines.extend(expr_lines)
            return lines, errors

        out_to_ins: Dict[str, List[str]] = {}
        for in_pin, out_pin in exec_in_to_out.items():
            out_to_ins.setdefault(out_pin, []).append(in_pin)

        def node_exec_out_pin(n: NodeData, name: str) -> Optional[str]:
            for p in n.outputs:
                if p.pin_type == "exec" and p.name == name:
                    return p.pin_id
            return None

        def node_out_pin(n: NodeData, name: str) -> Optional[str]:
            for p in n.outputs:
                if p.name == name:
                    return p.pin_id
            return None

        def next_node_from_exec_out(exec_out_pin: Optional[str]) -> Optional[str]:
            if not exec_out_pin:
                return None
            ins = out_to_ins.get(exec_out_pin, [])
            if len(ins) == 0:
                return None
            if len(ins) > 1:
                errors.append("An exec output connects to multiple nodes. Add a Sequence node.")
                return None
            return pin_to_node[ins[0]][0]

        def null_lit() -> str:
            return "None" if isinstance(r, PythonRenderer) else "null"

        def resolve_input_expr_with_exec(
            node: NodeData,
            input_name: str,
            required: bool,
        ) -> Optional[str]:
            pin = next((p for p in node.inputs if p.name == input_name), None)
            if not pin:
                if required:
                    errors.append(f"Node '{node.title}' missing expected input pin: {input_name}")
                return None
            if pin.pin_id not in data_in_to_out:
                if required:
                    errors.append(f"Node '{node.title}' missing input connection: {input_name}")
                return None
            src_out_pin = data_in_to_out[pin.pin_id]
            if src_out_pin in out_expr:
                return out_expr[src_out_pin]
            if src_out_pin in exec_out_expr:
                return exec_out_expr[src_out_pin]
            if required:
                errors.append(f"Node '{node.title}' input '{input_name}' depends on unresolved output.")
            return None

        def resolve_value(node: NodeData, input_name: str) -> str:
            v = resolve_input_expr_with_exec(node, input_name, required=True)
            return v if v is not None else null_lit()

        def resolve_value_optional(node: NodeData, input_name: str) -> str:
            v = resolve_input_expr_with_exec(node, input_name, required=False)
            return v if v is not None else null_lit()

        def loop_index_var(n: NodeData) -> str:
            return f"i_{n.node_id[:8]}"

        def emit_until_merge(start_exec_out_pin: Optional[str], local_seen: Set[str], in_loop: bool) -> Optional[str]:
            nxt = next_node_from_exec_out(start_exec_out_pin)
            while nxt is not None:
                if nxt in local_seen:
                    errors.append("Exec flow cycle detected (use loop nodes).")
                    return None
                local_seen.add(nxt)

                n = self.nodes.get(nxt)
                if not n:
                    return None

                if n.kind == "merge_exec":
                    return n.node_id

                # Sequence (Exec): run out_1 then out_2, both must converge
                if n.kind == "sequence_exec":
                    out1 = node_exec_out_pin(n, "exec_out_1")
                    out2 = node_exec_out_pin(n, "exec_out_2")

                    m1 = emit_until_merge(out1, set(), in_loop=in_loop) if out1 else None
                    m2 = emit_until_merge(out2, set(), in_loop=in_loop) if out2 else None

                    if m1 and m2 and m1 == m2:
                        merge_node = self.nodes[m1]
                        out_pin = node_exec_out_pin(merge_node, "exec_out")
                        nxt = next_node_from_exec_out(out_pin)
                        continue

                    if m1 is None and m2 is None:
                        return None

                    errors.append("Sequence branches must converge to the same Merge node.")
                    return None

                if n.kind == "print_exec":
                    r.emit_print(resolve_value(n, "value"))
                    nxt = next_node_from_exec_out(node_exec_out_pin(n, "exec_out"))
                    continue

                if n.kind == "set_var_exec":
                    name = sanitize_identifier(str(n.props.get("name", "x")), "x")
                    val = resolve_value(n, "value")
                    r.emit_assign(name, val)
                    nxt = next_node_from_exec_out(node_exec_out_pin(n, "exec_out"))
                    continue

                if n.kind == "inc_var_exec":
                    name = sanitize_identifier(str(n.props.get("name", "x")), "x")
                    r.emit_assign(name, f"({name}) + (1)")
                    nxt = next_node_from_exec_out(node_exec_out_pin(n, "exec_out"))
                    continue

                if n.kind == "add_to_var_exec":
                    name = sanitize_identifier(str(n.props.get("name", "x")), "x")
                    val = resolve_value(n, "value")
                    r.emit_assign(name, f"({name}) + ({val})")
                    nxt = next_node_from_exec_out(node_exec_out_pin(n, "exec_out"))
                    continue

                if n.kind == "sub_from_var_exec":
                    name = sanitize_identifier(str(n.props.get("name", "x")), "x")
                    val = resolve_value(n, "value")
                    r.emit_assign(name, f"({name}) - ({val})")
                    nxt = next_node_from_exec_out(node_exec_out_pin(n, "exec_out"))
                    continue

                # NEW: Maya Create Locator (Exec)
                if n.kind == "maya_create_locator_exec":
                    if not isinstance(r, (PythonRenderer, MayaPythonRenderer)):
                        errors.append("Maya nodes can only export to Python/Maya Python profiles.")
                        return None

                    nm = resolve_value_optional(n, "name")
                    x = resolve_value_optional(n, "x")
                    y = resolve_value_optional(n, "y")
                    z = resolve_value_optional(n, "z")

                    loc_tmp = f"loc_{n.node_id[:8]}"
                    w.write(f"{loc_tmp} = cmds.spaceLocator(name={nm})[0]")
                    w.write(f"cmds.move({x}, {y}, {z}, {loc_tmp}, absolute=True)")

                    out_loc_pin = node_out_pin(n, "locator")
                    if out_loc_pin:
                        exec_out_expr[out_loc_pin] = loc_tmp

                    nxt = next_node_from_exec_out(node_exec_out_pin(n, "exec_out"))
                    continue

                # List Append (Exec) - permissive + warnings
                if n.kind == "list_append_exec":
                    lst = resolve_value_optional(n, "list")
                    val = resolve_value_optional(n, "value")
                    self._warn(
                        n,
                        "LIST_APPEND_PERMISSIVE",
                        "List Append is permissive: if list is null/None or invalid, it becomes a no-op.",
                    )
                    w.write(f"__fp_list_append({lst}, {val})")
                    nxt = next_node_from_exec_out(node_exec_out_pin(n, "exec_out"))
                    continue

                # Map Set (Exec) - permissive + warnings
                if n.kind == "map_set_exec":
                    mp = resolve_value_optional(n, "map")
                    key = resolve_value_optional(n, "key")
                    val = resolve_value_optional(n, "value")
                    self._warn(
                        n,
                        "MAP_SET_PERMISSIVE",
                        "Map Set is permissive: if map is null/None or invalid, it becomes a no-op.",
                    )
                    w.write(f"__fp_map_set({mp}, {key}, {val})")
                    nxt = next_node_from_exec_out(node_exec_out_pin(n, "exec_out"))
                    continue

                if n.kind == "break_exec":
                    if not in_loop:
                        errors.append("Break (Exec) used outside of a loop.")
                        return None
                    r.emit_break()
                    return None

                if n.kind == "continue_exec":
                    if not in_loop:
                        errors.append("Continue (Exec) used outside of a loop.")
                        return None
                    r.emit_continue()
                    return None

                # ForEach Range (Exec)
                if n.kind == "foreach_range_exec":
                    i_var = loop_index_var(n)
                    start_expr = resolve_value(n, "start")
                    end_expr = resolve_value(n, "end")

                    r.begin_for_range(i_var, start_expr, end_expr)

                    body_pin = node_exec_out_pin(n, "loop_body")
                    before_body = len(w.lines)
                    if body_pin:
                        emit_until_merge(body_pin, set(), in_loop=True)
                    if len(w.lines) == before_body:
                        r.emit_pass()

                    r.end_for_range()

                    done_pin = node_exec_out_pin(n, "completed")
                    nxt = next_node_from_exec_out(done_pin)
                    continue

                if n.kind == "if_exec":
                    cond = resolve_value(n, "cond")
                    r.begin_if(cond)

                    then_pin = node_exec_out_pin(n, "then")
                    before_then = len(w.lines)
                    m_then = emit_until_merge(then_pin, set(), in_loop=in_loop) if then_pin else None
                    if len(w.lines) == before_then:
                        r.emit_pass()

                    r.else_block()
                    else_pin = node_exec_out_pin(n, "else")
                    before_else = len(w.lines)
                    m_else = emit_until_merge(else_pin, set(), in_loop=in_loop) if else_pin else None
                    if len(w.lines) == before_else:
                        r.emit_pass()

                    r.end_if()

                    if m_then and m_else and m_then == m_else:
                        merge_node = self.nodes[m_then]
                        out_pin = node_exec_out_pin(merge_node, "exec_out")
                        nxt = next_node_from_exec_out(out_pin)
                        continue

                    return None

                errors.append(f"Exec node kind not implemented: {n.kind}")
                return None

            return None

        emit_until_merge(start_exec_out, set(), in_loop=False)

        lines = r.header()
        rh = r.runtime_helpers()
        lines.extend(rh)
        if rh:
            lines.append("")
        lines.extend(expr_lines)
        if expr_lines:
            lines.append("")
        lines.extend(w.lines)
        return lines, errors

    # -----------------------------
    # Data expressions builder
    # -----------------------------
    def _build_data_expressions(
        self,
        r: BaseRenderer,
        pin_to_node: Dict[str, Tuple[str, bool, str, str]],
        data_in_to_out: Dict[str, str],
    ) -> Tuple[Dict[str, str], List[str], List[str]]:
        errors: List[str] = []
        lines: List[str] = []
        out_expr: Dict[str, str] = {}

        deps: Dict[str, Set[str]] = {nid: set() for nid in self.nodes}
        rev: Dict[str, Set[str]] = {nid: set() for nid in self.nodes}

        for in_pin_id, out_pin_id in data_in_to_out.items():
            prod = pin_to_node[out_pin_id][0]
            cons = pin_to_node[in_pin_id][0]
            if prod != cons:
                deps[cons].add(prod)
                rev[prod].add(cons)

        ready = [nid for nid in self.nodes if len(deps[nid]) == 0]
        order: List[str] = []
        while ready:
            nid = ready.pop()
            order.append(nid)
            for nxt in list(rev[nid]):
                deps[nxt].discard(nid)
                if len(deps[nxt]) == 0:
                    ready.append(nxt)

        if len(order) != len(self.nodes):
            errors.append("Data graph contains a cycle (loops not supported in data graph).")
            return out_expr, lines, errors

        valid_ops = {"==", "!=", ">", "<", ">=", "<="}

        def node_var(nid: str) -> str:
            return "n_" + nid[:8]

        def loop_index_name(nid: str) -> str:
            return f"i_{nid[:8]}"

        def loop_item_name(nid: str) -> str:
            return f"item_{nid[:8]}"

        def loop_key_name(nid: str) -> str:
            return f"key_{nid[:8]}"

        def loop_value_name(nid: str) -> str:
            return f"value_{nid[:8]}"

        def looks_like_runtime_var(s: str) -> bool:
            s = (s or "").strip()
            if s.startswith(("i_", "item_", "key_", "value_")):
                return True
            if s.startswith("n_"):
                return False
            return s.isidentifier()

        def null_lit() -> str:
            return "None" if isinstance(r, PythonRenderer) else "null"

        def is_int_literal(expr: str) -> bool:
            try:
                int(expr.strip())
                return True
            except Exception:
                return False

        for nid in order:
            n = self.nodes[nid]

            # Loop outputs are runtime vars (so you can use them in expressions)
            if n.kind == "foreach_range_exec":
                idx_pin = next((p for p in n.outputs if p.name == "index"), None)
                if idx_pin:
                    out_expr[idx_pin.pin_id] = loop_index_name(nid)

            # Existing nodes
            if n.kind == "const_int":
                v = n.props.get("value", 0)
                try:
                    out_expr[n.outputs[0].pin_id] = str(int(v))
                except Exception:
                    errors.append(f"Const Int node has invalid value: {v}")
                    out_expr[n.outputs[0].pin_id] = "0"

            elif n.kind == "const_string":
                v = str(n.props.get("value", ""))
                out_expr[n.outputs[0].pin_id] = repr(v)

            elif n.kind == "get_var":
                name = sanitize_identifier(str(n.props.get("name", "x")), "x")
                out_expr[n.outputs[0].pin_id] = name

            elif n.kind == "get_param":
                name = sanitize_identifier(str(n.props.get("name", "param")), "param")
                out_expr[n.outputs[0].pin_id] = name

            elif n.kind == "make_list_empty":
                out_expr[n.outputs[0].pin_id] = "[]"

            # Make List (N): make_list_1 .. make_list_6
            elif n.kind.startswith("make_list_"):
                try:
                    count = int(n.kind.split("_")[-1])
                except Exception:
                    count = 0

                items: List[str] = []
                for i in range(1, count + 1):
                    pin_name = f"item_{i}"
                    v = self._try_resolve_input_expr(n, pin_name, pin_to_node, data_in_to_out, out_expr)
                    if v is None:
                        self._warn(
                            n,
                            "MAKE_LIST_MISSING_ITEM",
                            f"Make List({count}) missing input '{pin_name}'; using {null_lit()}.",
                        )
                        v = null_lit()
                    items.append(v)

                out_expr[n.outputs[0].pin_id] = "[" + ", ".join(items) + "]"

            elif n.kind == "make_map_empty":
                out_expr[n.outputs[0].pin_id] = "{}"

            elif n.kind == "list_get":
                lst = self._try_resolve_input_expr(n, "list", pin_to_node, data_in_to_out, out_expr)
                idx = self._try_resolve_input_expr(n, "index", pin_to_node, data_in_to_out, out_expr)
                if lst is None or idx is None:
                    self._warn(n, "LIST_GET_MISSING_INPUT", "List Get missing list/index; using None/null.")
                    out_expr[n.outputs[0].pin_id] = null_lit()
                    continue

                if lst.strip() == "[]" and is_int_literal(idx):
                    self._warn(n, "LIST_GET_OOB_LITERAL", f"List Get indexes empty literal list at {idx}.")
                out_expr[n.outputs[0].pin_id] = f"__fp_list_get({lst}, {idx})"

            elif n.kind == "list_len":
                lst = self._try_resolve_input_expr(n, "list", pin_to_node, data_in_to_out, out_expr)
                if lst is None:
                    self._warn(n, "LIST_LEN_MISSING_INPUT", "List Length missing list; using 0.")
                    out_expr[n.outputs[0].pin_id] = "0"
                    continue
                out_expr[n.outputs[0].pin_id] = f"__fp_list_len({lst})"

            elif n.kind == "map_get":
                mp = self._try_resolve_input_expr(n, "map", pin_to_node, data_in_to_out, out_expr)
                key = self._try_resolve_input_expr(n, "key", pin_to_node, data_in_to_out, out_expr)
                if mp is None or key is None:
                    self._warn(n, "MAP_GET_MISSING_INPUT", "Map Get missing map/key; using None/null.")
                    out_expr[n.outputs[0].pin_id] = null_lit()
                    continue
                out_expr[n.outputs[0].pin_id] = f"__fp_map_get({mp}, {key})"

            elif n.kind == "add_int":
                a = self._resolve_input_expr(n, "a", pin_to_node, data_in_to_out, out_expr, errors)
                b = self._resolve_input_expr(n, "b", pin_to_node, data_in_to_out, out_expr, errors)
                if a is None or b is None:
                    continue

                if looks_like_runtime_var(a) or looks_like_runtime_var(b):
                    out_expr[n.outputs[0].pin_id] = f"({a}) + ({b})"
                    continue

                tmp = node_var(nid) + "_result"
                if isinstance(r, ToonBoomJSRenderer):
                    lines.append(f"var {tmp} = ({a}) + ({b});")
                else:
                    lines.append(f"{tmp} = ({a}) + ({b})")
                out_expr[n.outputs[0].pin_id] = tmp

            # NEW: Multiply (int)
            elif n.kind == "mul_int":
                a = self._resolve_input_expr(n, "a", pin_to_node, data_in_to_out, out_expr, errors)
                b = self._resolve_input_expr(n, "b", pin_to_node, data_in_to_out, out_expr, errors)
                if a is None or b is None:
                    continue

                if looks_like_runtime_var(a) or looks_like_runtime_var(b):
                    out_expr[n.outputs[0].pin_id] = f"({a}) * ({b})"
                    continue

                tmp = node_var(nid) + "_mul"
                if isinstance(r, ToonBoomJSRenderer):
                    lines.append(f"var {tmp} = ({a}) * ({b});")
                else:
                    lines.append(f"{tmp} = ({a}) * ({b})")
                out_expr[n.outputs[0].pin_id] = tmp

            elif n.kind == "compare_int":
                a = self._resolve_input_expr(n, "a", pin_to_node, data_in_to_out, out_expr, errors)
                b = self._resolve_input_expr(n, "b", pin_to_node, data_in_to_out, out_expr, errors)
                if a is None or b is None:
                    continue

                op = str(n.props.get("op", ">")).strip()
                if op not in valid_ops:
                    errors.append(f"Compare node '{n.title}' has invalid operator: {op}")
                    op = ">"

                if looks_like_runtime_var(a) or looks_like_runtime_var(b):
                    out_expr[n.outputs[0].pin_id] = f"(({a}) {op} ({b}))"
                    continue

                tmp = node_var(nid) + "_cmp"
                if isinstance(r, ToonBoomJSRenderer):
                    lines.append(f"var {tmp} = ({a}) {op} ({b});")
                else:
                    lines.append(f"{tmp} = ({a}) {op} ({b})")
                out_expr[n.outputs[0].pin_id] = tmp

            elif n.kind == "branch":
                cond = self._resolve_input_expr(n, "cond", pin_to_node, data_in_to_out, out_expr, errors)
                tval = self._resolve_input_expr(n, "then", pin_to_node, data_in_to_out, out_expr, errors)
                eval_ = self._resolve_input_expr(n, "else", pin_to_node, data_in_to_out, out_expr, errors)
                if cond is None or tval is None or eval_ is None:
                    continue
                if isinstance(r, ToonBoomJSRenderer):
                    out_expr[n.outputs[0].pin_id] = f"({cond}) ? ({tval}) : ({eval_})"
                else:
                    out_expr[n.outputs[0].pin_id] = f"({tval}) if ({cond}) else ({eval_})"

        return out_expr, lines, errors

    def _try_resolve_input_expr(
        self,
        node: NodeData,
        input_name: str,
        pin_to_node: Dict[str, Tuple[str, bool, str, str]],
        data_in_to_out: Dict[str, str],
        out_expr: Dict[str, str],
    ) -> Optional[str]:
        """
        Permissive version: does NOT add errors.
        Returns None if missing.
        """
        pin = next((p for p in node.inputs if p.name == input_name), None)
        if not pin:
            return None
        if pin.pin_id not in data_in_to_out:
            return None
        src_out_pin = data_in_to_out[pin.pin_id]
        return out_expr.get(src_out_pin)

    def _resolve_input_expr(
        self,
        node: NodeData,
        input_name: str,
        pin_to_node: Dict[str, Tuple[str, bool, str, str]],
        data_in_to_out: Dict[str, str],
        out_expr: Dict[str, str],
        errors: List[str],
    ) -> Optional[str]:
        pin = next((p for p in node.inputs if p.name == input_name), None)
        if not pin:
            errors.append(f"Node '{node.title}' missing expected input pin: {input_name}")
            return None
        if pin.pin_id not in data_in_to_out:
            errors.append(f"Node '{node.title}' missing input connection: {input_name}")
            return None
        src_out_pin = data_in_to_out[pin.pin_id]
        if src_out_pin not in out_expr:
            errors.append(f"Node '{node.title}' input '{input_name}' depends on unresolved output.")
            return None
        return out_expr[src_out_pin]